package com.jfinal.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZoWebsiteArticleTag<M extends BaseZoWebsiteArticleTag<M>> extends Model<M> implements IBean {

	public void setZoWebsiteArticleTagId(java.lang.String zoWebsiteArticleTagId) {
		set("zo_website_article_tag_id", zoWebsiteArticleTagId);
	}
	
	public java.lang.String getZoWebsiteArticleTagId() {
		return getStr("zo_website_article_tag_id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setColor(java.lang.String color) {
		set("color", color);
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}
	
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}
	
	public java.lang.String getDeleted() {
		return getStr("deleted");
	}
	
	public void setSortOrder(java.lang.Long sortOrder) {
		set("sort_order", sortOrder);
	}
	
	public java.lang.Long getSortOrder() {
		return getLong("sort_order");
	}
	
}
