package com.jfinal.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZoWebsiteApi<M extends BaseZoWebsiteApi<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setZoWebsiteApiId(java.lang.String zoWebsiteApiId) {
		set("zo_website_api_id", zoWebsiteApiId);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getZoWebsiteApiId() {
		return getStr("zo_website_api_id");
	}
	
	/**
	 * API 名称（如：随机壁纸 API）
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * API 名称（如：随机壁纸 API）
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * API 描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * API 描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 请求地址（如：https://api.example.com/wallpaper）
	 */
	public void setEndpoint(java.lang.String endpoint) {
		set("endpoint", endpoint);
	}
	
	/**
	 * 请求地址（如：https://api.example.com/wallpaper）
	 */
	public java.lang.String getEndpoint() {
		return getStr("endpoint");
	}
	
	/**
	 * 请求方法
	 */
	public void setMethod(java.lang.String method) {
		set("method", method);
	}
	
	/**
	 * 请求方法
	 */
	public java.lang.String getMethod() {
		return getStr("method");
	}
	
	/**
	 * 关联分类标签 ID
	 */
	public void setTagValue(java.lang.String tagValue) {
		set("tag_value", tagValue);
	}
	
	/**
	 * 关联分类标签 ID
	 */
	public java.lang.String getTagValue() {
		return getStr("tag_value");
	}
	
	/**
	 * 标签
	 */
	public void setTagText(java.lang.String tagText) {
		set("tag_text", tagText);
	}
	
	/**
	 * 标签
	 */
	public java.lang.String getTagText() {
		return getStr("tag_text");
	}
	
	/**
	 * 是否免费：1-免费，0-付费
	 */
	public void setIsFree(java.lang.String isFree) {
		set("is_free", isFree);
	}
	
	/**
	 * 是否免费：1-免费，0-付费
	 */
	public java.lang.String getIsFree() {
		return getStr("is_free");
	}
	
	/**
	 * 返回格式（JSON / XML 等）
	 */
	public void setResponseFormat(java.lang.String responseFormat) {
		set("response_format", responseFormat);
	}
	
	/**
	 * 返回格式（JSON / XML 等）
	 */
	public java.lang.String getResponseFormat() {
		return getStr("response_format");
	}
	
	/**
	 * 请求示例（curl 命令等）
	 */
	public void setRequestExample(java.lang.String requestExample) {
		set("request_example", requestExample);
	}
	
	/**
	 * 请求示例（curl 命令等）
	 */
	public java.lang.String getRequestExample() {
		return getStr("request_example");
	}
	
	/**
	 * 返回示例（JSON 结构）
	 */
	public void setResponseExample(java.lang.String responseExample) {
		set("response_example", responseExample);
	}
	
	/**
	 * 返回示例（JSON 结构）
	 */
	public java.lang.String getResponseExample() {
		return getStr("response_example");
	}
	
	/**
	 * 状态：1-已上架，0-已下架
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态：1-已上架，0-已下架
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 点赞数
	 */
	public void setLikeCount(java.lang.String likeCount) {
		set("like_count", likeCount);
	}
	
	/**
	 * 点赞数
	 */
	public java.lang.String getLikeCount() {
		return getStr("like_count");
	}
	
	/**
	 * 删除状态
	 */
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}
	
	/**
	 * 删除状态
	 */
	public java.lang.String getDeleted() {
		return getStr("deleted");
	}
	
	/**
	 * 响应时长
	 */
	public void setResponseTime(java.lang.String responseTime) {
		set("response_time", responseTime);
	}
	
	/**
	 * 响应时长
	 */
	public java.lang.String getResponseTime() {
		return getStr("response_time");
	}
	
}
