package com.jfinal.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZoFile<M extends BaseZoFile<M>> extends Model<M> implements IBean {

	/**
	 * 主键，UUID
	 */
	public void setZoFileId(java.lang.String zoFileId) {
		set("zo_file_id", zoFileId);
	}
	
	/**
	 * 主键，UUID
	 */
	public java.lang.String getZoFileId() {
		return getStr("zo_file_id");
	}
	
	/**
	 * 原始文件名
	 */
	public void setOriginalName(java.lang.String originalName) {
		set("original_name", originalName);
	}
	
	/**
	 * 原始文件名
	 */
	public java.lang.String getOriginalName() {
		return getStr("original_name");
	}
	
	/**
	 * 存储文件名
	 */
	public void setStorageName(java.lang.String storageName) {
		set("storage_name", storageName);
	}
	
	/**
	 * 存储文件名
	 */
	public java.lang.String getStorageName() {
		return getStr("storage_name");
	}
	
	/**
	 * 文件存储路径
	 */
	public void setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
	}
	
	/**
	 * 文件存储路径
	 */
	public java.lang.String getFilePath() {
		return getStr("file_path");
	}
	
	/**
	 * 文件大小（字节）
	 */
	public void setFileSize(java.lang.Long fileSize) {
		set("file_size", fileSize);
	}
	
	/**
	 * 文件大小（字节）
	 */
	public java.lang.Long getFileSize() {
		return getLong("file_size");
	}
	
	/**
	 * 文件类型（MIME）
	 */
	public void setFileType(java.lang.String fileType) {
		set("file_type", fileType);
	}
	
	/**
	 * 文件类型（MIME）
	 */
	public java.lang.String getFileType() {
		return getStr("file_type");
	}
	
	/**
	 * 文件扩展名
	 */
	public void setFileExtension(java.lang.String fileExtension) {
		set("file_extension", fileExtension);
	}
	
	/**
	 * 文件扩展名
	 */
	public java.lang.String getFileExtension() {
		return getStr("file_extension");
	}
	
	/**
	 * 存储桶名称（MinIO使用）
	 */
	public void setBucketName(java.lang.String bucketName) {
		set("bucket_name", bucketName);
	}
	
	/**
	 * 存储桶名称（MinIO使用）
	 */
	public java.lang.String getBucketName() {
		return getStr("bucket_name");
	}
	
	/**
	 * 上传用户ID
	 */
	public void setUploaderId(java.lang.String uploaderId) {
		set("uploader_id", uploaderId);
	}
	
	/**
	 * 上传用户ID
	 */
	public java.lang.String getUploaderId() {
		return getStr("uploader_id");
	}
	
	/**
	 * 上传时间
	 */
	public void setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getUploadTime() {
		return get("upload_time");
	}
	
	/**
	 * 下载次数
	 */
	public void setDownloadCount(java.lang.Integer downloadCount) {
		set("download_count", downloadCount);
	}
	
	/**
	 * 下载次数
	 */
	public java.lang.Integer getDownloadCount() {
		return getInt("download_count");
	}
	
	/**
	 * 文件描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 文件描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 是否公开访问
	 */
	public void setIsPublic(java.lang.Boolean isPublic) {
		set("is_public", isPublic);
	}
	
	/**
	 * 是否公开访问
	 */
	public java.lang.Boolean getIsPublic() {
		return get("is_public");
	}
	
	/**
	 * 状态（1-正常，0-禁用）
	 */
	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}
	
	/**
	 * 状态（1-正常，0-禁用）
	 */
	public java.lang.Boolean getStatus() {
		return get("status");
	}
	
	/**
	 * 版本号（乐观锁）
	 */
	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}
	
	/**
	 * 版本号（乐观锁）
	 */
	public java.lang.Integer getVersion() {
		return getInt("version");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 逻辑删除标志
	 */
	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}
	
	/**
	 * 逻辑删除标志
	 */
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}
	
	/**
	 * 文件MD5哈希值
	 */
	public void setMd5Hash(java.lang.String md5Hash) {
		set("md5_hash", md5Hash);
	}
	
	/**
	 * 文件MD5哈希值
	 */
	public java.lang.String getMd5Hash() {
		return getStr("md5_hash");
	}
	
}
