package com.jfinal.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZoWebsiteApiTag<M extends BaseZoWebsiteApiTag<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setZoWebsiteApiTagId(java.lang.String zoWebsiteApiTagId) {
		set("zo_website_api_tag_id", zoWebsiteApiTagId);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getZoWebsiteApiTagId() {
		return getStr("zo_website_api_tag_id");
	}
	
	/**
	 * 标签名称（如：工具、AI、图片、生活）
	 */
	public void setTagName(java.lang.String tagName) {
		set("tag_name", tagName);
	}
	
	/**
	 * 标签名称（如：工具、AI、图片、生活）
	 */
	public java.lang.String getTagName() {
		return getStr("tag_name");
	}
	
	/**
	 * 标签颜色（HEX）
	 */
	public void setTagColor(java.lang.String tagColor) {
		set("tag_color", tagColor);
	}
	
	/**
	 * 标签颜色（HEX）
	 */
	public java.lang.String getTagColor() {
		return getStr("tag_color");
	}
	
	/**
	 * 排序权重，越大越靠前
	 */
	public void setSortOrder(java.lang.Integer sortOrder) {
		set("sort_order", sortOrder);
	}
	
	/**
	 * 排序权重，越大越靠前
	 */
	public java.lang.Integer getSortOrder() {
		return getInt("sort_order");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}
	
	public java.lang.String getDeleted() {
		return getStr("deleted");
	}
	
}
