package com.jfinal.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZoWebsiteApiCallLog<M extends BaseZoWebsiteApiCallLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setZoWebsiteApiCallLogId(java.lang.String zoWebsiteApiCallLogId) {
		set("zo_website_api_call_log_id", zoWebsiteApiCallLogId);
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getZoWebsiteApiCallLogId() {
		return getStr("zo_website_api_call_log_id");
	}
	
	/**
	 * 关联 API ID
	 */
	public void setApiId(java.math.BigInteger apiId) {
		set("api_id", apiId);
	}
	
	/**
	 * 关联 API ID
	 */
	public java.math.BigInteger getApiId() {
		return get("api_id");
	}
	
	/**
	 * 调用用户 ID（未登录则为 NULL）
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 调用用户 ID（未登录则为 NULL）
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 调用方 IP
	 */
	public void setClientIp(java.lang.String clientIp) {
		set("client_ip", clientIp);
	}
	
	/**
	 * 调用方 IP
	 */
	public java.lang.String getClientIp() {
		return getStr("client_ip");
	}
	
	/**
	 * HTTP 状态码（200 / 400 / 500 等）
	 */
	public void setStatusCode(java.lang.Integer statusCode) {
		set("status_code", statusCode);
	}
	
	/**
	 * HTTP 状态码（200 / 400 / 500 等）
	 */
	public java.lang.Integer getStatusCode() {
		return getInt("status_code");
	}
	
	/**
	 * 接口响应耗时（毫秒）
	 */
	public void setResponseTime(java.lang.Long responseTime) {
		set("response_time", responseTime);
	}
	
	/**
	 * 接口响应耗时（毫秒）
	 */
	public java.lang.Long getResponseTime() {
		return getLong("response_time");
	}
	
	/**
	 * 请求参数快照
	 */
	public void setRequestParams(java.lang.String requestParams) {
		set("request_params", requestParams);
	}
	
	/**
	 * 请求参数快照
	 */
	public java.lang.String getRequestParams() {
		return getStr("request_params");
	}
	
	/**
	 * 调用时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 调用时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
}
