package com.jfinal.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZoWebsiteArticle<M extends BaseZoWebsiteArticle<M>> extends Model<M> implements IBean {

	public void setZoWebsiteArticleId(java.lang.String zoWebsiteArticleId) {
		set("zo_website_article_id", zoWebsiteArticleId);
	}
	
	public java.lang.String getZoWebsiteArticleId() {
		return getStr("zo_website_article_id");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setTagValue(java.lang.String tagValue) {
		set("tag_value", tagValue);
	}
	
	public java.lang.String getTagValue() {
		return getStr("tag_value");
	}
	
	public void setTagText(java.lang.String tagText) {
		set("tag_text", tagText);
	}
	
	public java.lang.String getTagText() {
		return getStr("tag_text");
	}
	
	public void setAuthorId(java.lang.String authorId) {
		set("author_id", authorId);
	}
	
	public java.lang.String getAuthorId() {
		return getStr("author_id");
	}
	
	public void setAuthorName(java.lang.String authorName) {
		set("author_name", authorName);
	}
	
	public java.lang.String getAuthorName() {
		return getStr("author_name");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
	/**
	 * 最后更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	/**
	 * 最后更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}
	
	/**
	 * 发布时间（可为空，表示未发布）
	 */
	public void setPublishTime(java.util.Date publishTime) {
		set("publish_time", publishTime);
	}
	
	/**
	 * 发布时间（可为空，表示未发布）
	 */
	public java.util.Date getPublishTime() {
		return get("publish_time");
	}
	
	/**
	 * 推荐阅读时长（分钟，默认5分钟）
	 */
	public void setRecommendReadTime(java.lang.Integer recommendReadTime) {
		set("recommend_read_time", recommendReadTime);
	}
	
	/**
	 * 推荐阅读时长（分钟，默认5分钟）
	 */
	public java.lang.Integer getRecommendReadTime() {
		return getInt("recommend_read_time");
	}
	
	public void setCoverGradient(java.lang.String coverGradient) {
		set("cover_gradient", coverGradient);
	}
	
	public java.lang.String getCoverGradient() {
		return getStr("cover_gradient");
	}
	
	public void setCoverImage(java.lang.String coverImage) {
		set("cover_image", coverImage);
	}
	
	public java.lang.String getCoverImage() {
		return getStr("cover_image");
	}
	
	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}
	
	public java.lang.String getSummary() {
		return getStr("summary");
	}
	
	/**
	 * 点赞数
	 */
	public void setLikeCount(java.lang.Integer likeCount) {
		set("like_count", likeCount);
	}
	
	/**
	 * 点赞数
	 */
	public java.lang.Integer getLikeCount() {
		return getInt("like_count");
	}
	
	/**
	 * 阅读量
	 */
	public void setViewCount(java.lang.Integer viewCount) {
		set("view_count", viewCount);
	}
	
	/**
	 * 阅读量
	 */
	public java.lang.Integer getViewCount() {
		return getInt("view_count");
	}
	
	/**
	 * 评论数（建议添加）
	 */
	public void setCommentCount(java.lang.Integer commentCount) {
		set("comment_count", commentCount);
	}
	
	/**
	 * 评论数（建议添加）
	 */
	public java.lang.Integer getCommentCount() {
		return getInt("comment_count");
	}
	
	public void setStatusValue(java.lang.String statusValue) {
		set("status_value", statusValue);
	}
	
	public java.lang.String getStatusValue() {
		return getStr("status_value");
	}
	
	public void setStatusText(java.lang.String statusText) {
		set("status_text", statusText);
	}
	
	public java.lang.String getStatusText() {
		return getStr("status_text");
	}
	
	/**
	 * 是否置顶：0-否 1-是
	 */
	public void setIsTop(java.lang.Boolean isTop) {
		set("is_top", isTop);
	}
	
	/**
	 * 是否置顶：0-否 1-是
	 */
	public java.lang.Boolean getIsTop() {
		return get("is_top");
	}
	
	/**
	 * 是否热门：0-否 1-是
	 */
	public void setIsHot(java.lang.Boolean isHot) {
		set("is_hot", isHot);
	}
	
	/**
	 * 是否热门：0-否 1-是
	 */
	public java.lang.Boolean getIsHot() {
		return get("is_hot");
	}
	
	/**
	 * 是否推荐：0-否 1-是
	 */
	public void setIsRecommend(java.lang.Boolean isRecommend) {
		set("is_recommend", isRecommend);
	}
	
	/**
	 * 是否推荐：0-否 1-是
	 */
	public java.lang.Boolean getIsRecommend() {
		return get("is_recommend");
	}
	
	/**
	 * 排序权重（数字越大越靠前）
	 */
	public void setSortOrder(java.lang.Integer sortOrder) {
		set("sort_order", sortOrder);
	}
	
	/**
	 * 排序权重（数字越大越靠前）
	 */
	public java.lang.Integer getSortOrder() {
		return getInt("sort_order");
	}
	
	public void setSeoTitle(java.lang.String seoTitle) {
		set("seo_title", seoTitle);
	}
	
	public java.lang.String getSeoTitle() {
		return getStr("seo_title");
	}
	
	public void setSeoKeywords(java.lang.String seoKeywords) {
		set("seo_keywords", seoKeywords);
	}
	
	public java.lang.String getSeoKeywords() {
		return getStr("seo_keywords");
	}
	
	public void setSeoDescription(java.lang.String seoDescription) {
		set("seo_description", seoDescription);
	}
	
	public java.lang.String getSeoDescription() {
		return getStr("seo_description");
	}
	
	/**
	 * 软删除标记：0-正常 1-删除
	 */
	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}
	
	/**
	 * 软删除标记：0-正常 1-删除
	 */
	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}
	
}
