package com.jfinal.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZoWebsiteApiParam<M extends BaseZoWebsiteApiParam<M>> extends Model<M> implements IBean {

	public void setZoWebsiteApiParamId(java.lang.String zoWebsiteApiParamId) {
		set("zo_website_api_param_id", zoWebsiteApiParamId);
	}
	
	public java.lang.String getZoWebsiteApiParamId() {
		return getStr("zo_website_api_param_id");
	}
	
	/**
	 * 参数名
	 */
	public void setPara(java.lang.String para) {
		set("para", para);
	}
	
	/**
	 * 参数名
	 */
	public java.lang.String getPara() {
		return getStr("para");
	}
	
	/**
	 * 参数描述
	 */
	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}
	
	/**
	 * 参数描述
	 */
	public java.lang.String getDesc() {
		return getStr("desc");
	}
	
	/**
	 * 参数类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 参数类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 传入方法
	 */
	public void setMethod(java.lang.String method) {
		set("method", method);
	}
	
	/**
	 * 传入方法
	 */
	public java.lang.String getMethod() {
		return getStr("method");
	}
	
	/**
	 * 是否必填
	 */
	public void setRequired(java.lang.String required) {
		set("required", required);
	}
	
	/**
	 * 是否必填
	 */
	public java.lang.String getRequired() {
		return getStr("required");
	}
	
	/**
	 * 默认值
	 */
	public void setDefaultValue(java.lang.String defaultValue) {
		set("default_value", defaultValue);
	}
	
	/**
	 * 默认值
	 */
	public java.lang.String getDefaultValue() {
		return getStr("default_value");
	}
	
	/**
	 * 是否删除
	 */
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.String getDeleted() {
		return getStr("deleted");
	}
	
	public void setZoWebsiteApiId(java.lang.String zoWebsiteApiId) {
		set("zo_website_api_id", zoWebsiteApiId);
	}
	
	public java.lang.String getZoWebsiteApiId() {
		return getStr("zo_website_api_id");
	}
	
}
