package com.jfinal.model;

import com.jfinal.model.BaseZoFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoFile extends BaseZoFile<ZoFile> {
	public static final ZoFile dao = new ZoFile().dao();
}
