package com.jfinal.model;

import com.jfinal.model.BaseZoWebsiteApiCallLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoWebsiteApiCallLog extends BaseZoWebsiteApiCallLog<ZoWebsiteApiCallLog> {
	public static final ZoWebsiteApiCallLog dao = new ZoWebsiteApiCallLog().dao();
}
