package com.jfinal.model;

import com.jfinal.model.BaseZoWebsiteArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoWebsiteArticle extends BaseZoWebsiteArticle<ZoWebsiteArticle> {
	public static final ZoWebsiteArticle dao = new ZoWebsiteArticle().dao();
}
