package com.jfinal.model;

import com.jfinal.model.BaseZoWebsiteArticleTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoWebsiteArticleTag extends BaseZoWebsiteArticleTag<ZoWebsiteArticleTag> {
	public static final ZoWebsiteArticleTag dao = new ZoWebsiteArticleTag().dao();
}
