package com.jfinal.model;

import com.jfinal.model.BaseZoWebsiteApiParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoWebsiteApiParam extends BaseZoWebsiteApiParam<ZoWebsiteApiParam> {
	public static final ZoWebsiteApiParam dao = new ZoWebsiteApiParam().dao();
}
