package com.jfinal.model;

import com.jfinal.model.BaseZoWebsiteApiTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoWebsiteApiTag extends BaseZoWebsiteApiTag<ZoWebsiteApiTag> {
	public static final ZoWebsiteApiTag dao = new ZoWebsiteApiTag().dao();
}
