package com.jfinal.model;

import com.jfinal.model.BaseZoWebsiteApi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZoWebsiteApi extends BaseZoWebsiteApi<ZoWebsiteApi> {
	public static final ZoWebsiteApi dao = new ZoWebsiteApi().dao();
}
